// VCU CAN IDs
#define ID_MC_TEMPERATURES_1 0xA0
#define ID_MC_TEMPERATURES_2 0xA1
#define ID_MC_TEMPERATURES_3 0xA2
#define ID_MC_ANALOG_INPUTS_VOLTAGES 0xA3
#define ID_MC_DIGITAL_INPUT_STATUS 0xA4
#define ID_MC_MOTOR_POSITION_INFORMATION 0xA5
#define ID_MC_CURRENT_INFORMATION 0xA6
#define ID_MC_VOLTAGE_INFORMATION 0xA7
#define ID_MC_FLUX_INFORMATION 0xA8
#define ID_MC_INTERNAL_VOLTAGES 0xA9
#define ID_MC_INTERNAL_STATES 0xAA
#define ID_MC_FAULT_CODES 0xAB
#define ID_MC_TORQUE_TIMER_INFORMATION 0xAC
#define ID_MC_MODULATION_INDEX_FLUX_WEAKENING_OUTPUT_INFORMATION 0xAD
#define ID_MC_FIRMWARE_INFORMATION 0xAE
#define ID_MC_DIAGNOSTIC_DATA 0xAF
#define ID_MC_COMMAND_MESSAGE 0xC0
#define ID_MC_READ_WRITE_PARAMETER_COMMAND 0xC1
#define ID_MC_READ_WRITE_PARAMETER_RESPONSE 0xC2
#define ID_VCU_STATUS 0xC3
#define ID_VCU_PEDAL_READINGS 0xC4
#define ID_VCU_WS_READINGS 0xC6

// DASH CAN IDs
#define ID_DASH_BUTTONS 0xEB
#define ID_DASH_BUSVOLT 0xD4

// BMS CAN IDs
#define ID_BMS_INFO 0x6B1
#define ID_BMS_SOC 0x6B3 // made this real!

// ACU CAN IDs
#define ID_ACU_RELAY 0x68

#define MODULE_1_A 0x1A
#define MODULE_1_B 0x1B

#define MODULE_2_A 0x2A
#define MODULE_2_B 0x2B

#define MODULE_3_A 0x3A
#define MODULE_3_B 0x3B

#define MODULE_4_A 0x4A
#define MODULE_4_B 0x4B

#define MODULE_5_A 0x5A
#define MODULE_5_B 0x5B

#define MODULE_6_A 0x6A
#define MODULE_6_B 0x6B

// eveLogger CAN IDs for the Vector NAV unit
#define NAV_TIME = 0xNT
#define NAV_GYRO = 0xNG
#define NAV_RATE = 0xNR
#define NAV_PLLA = 0xNP
#define NAV_VELO = 0xNV
#define NAV_ACCL = 0xNA
